formatter: markdown
output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ "{{ .Content }}" }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

sections:
  hide:
    - header
    - resources
    - data-sources

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: false
  required: true
  sensitive: false
  type: true
